### ISSUE TITLE
What is it? When I try to enchant a item(sword), it's wrong.

### ISSUE THREAD

**Issue by Cqmmls** [Dumphey/item-editor#6]
[19:53:55 ERROR]: Could not pass event InventoryClickEvent to ItemEditor v2.0.1
java.lang.ExceptionInInitializerError: null
        at at.dumphey.itemeditor.itemeditor.modules.enchantments.screens.add.AddEnchantmentUiItem.onRender(AddEnchantmentUiItem.java:25) ~[ItemEditor-2.0.1.jar:?]
        at at.dumphey.itemeditor.ui.template.UiItem.render(UiItem.java:38) ~[ItemEditor-2.0.1.jar:?]
        at at.dumphey.itemeditor.utils.UiUtils.lambda$sortedByMaterialAndName$0(UiUtils.java:16) ~[ItemEditor-2.0.1.jar:?]
        at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:473) ~[?:?]
        at java.util.Comparator.lambda$thenComparing$36697e65$1(Comparator.java:220) ~[?:?]
        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?]
        at java.util.TimSort.sort(TimSort.java:234) ~[?:?]
        at java.util.Arrays.sort(Arrays.java:1307) ~[?:?]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at at.dumphey.itemeditor.utils.UiUtils.sortedByMaterialAndName(UiUtils.java:18) ~[ItemEditor-2.0.1.jar:?]
        at at.dumphey.itemeditor.itemeditor.modules.enchantments.screens.add.AddEnchantmentUiScreen.onUpdate(AddEnchantmentUiScreen.java:32) ~[ItemEditor-2.0.1.jar:?]
        at at.dumphey.itemeditor.ui.template.UiScreen.update(UiScreen.java:94) ~[ItemEditor-2.0.1.jar:?]
        at at.dumphey.itemeditor.ui.UiManager.update(UiManager.java:47) ~[ItemEditor-2.0.1.jar:?]
        at at.dumphey.itemeditor.ui.UiManager.open(UiManager.java:57) ~[ItemEditor-2.0.1.jar:?]
        at at.dumphey.itemeditor.ui.template.UiComponent.open(UiComponent.java:22) ~[ItemEditor-2.0.1.jar:?]
        at at.dumphey.itemeditor.itemeditor.modules.enchantments.screens.manage.OpenAddEnchantmentUiItem.onClick(OpenAddEnchantmentUiItem.java:26) ~[ItemEditor-2.0.1.jar:?]
        at at.dumphey.itemeditor.ui.template.UiItem.click(UiItem.java:62) ~[ItemEditor-2.0.1.jar:?]
        at at.dumphey.itemeditor.ui.template.UiScreen.onClick(UiScreen.java:122) ~[ItemEditor-2.0.1.jar:?]
        at at.dumphey.itemeditor.ui.UiManager.onInventoryClick(UiManager.java:37) ~[ItemEditor-2.0.1.jar:?]
        at at.dumphey.itemeditor.events.InventoryClickListener.onClick(InventoryClickListener.java:17) ~[ItemEditor-2.0.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2892) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1457) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1435) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1428) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1317) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-115]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:143) ~[?:?]
        at at.dumphey.itemeditor.itemeditor.modules.enchantments.EnchantUtils.getByEnumName(EnchantUtils.java:51) ~[ItemEditor-2.0.1.jar:?]
        at at.dumphey.itemeditor.itemeditor.modules.enchantments.EnchantUtils.<clinit>(EnchantUtils.java:37) ~[ItemEditor-2.0.1.jar:?]
        ... 47 more

**Comment by Cqmmls** [comment]
I tested in spigot 1.17.1 and initially judged to be your plugin issue? I hope the author can see the issue I posted soon, love this plugin very much, it is very simple to use.
